version: "3.8"

services:

  tg_bot:
    build:
      context: .
      dockerfile: Dockerfile.tg_bot
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - internal

  vk_bot:
    build:
      context: .
      dockerfile: Dockerfile.vk_bot
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - internal

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - internal

networks:
  internal:
    driver: bridge
